name: Release
'on':
  push:
    branches:
      - alpha
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    uses: form8ion/semantic-release-workflow/.github/workflows/release.yml@e289fa764e958143b31086c34248b354a642019b # v1.0.2
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
